name: Our first pipeline!

on: [push]

jobs:
  says-hi:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_VAR: "Hello from the workflow!"
    steps:
      - name: Echo
        run: |
          echo "hi"
          export PYTHON_VERSION=$(python --version)
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV
      - name: Print Python Version
        run: echo "${{env.PYTHON_VERSION}}" #Better work!
      - name: Print vars
        env:
          STEP_VAR: "hello from the environment!"
        run: |
          env
          echo ${{env.WORKFLOW_VAR}}
          echo ${{env.STEP_VAR}}
      - uses: actions/checkout@v2
      - name: List files
        run: ls
      - name: Runs howdy
        run: python sample.py