name: Our first pipeline!

on: [push]

jobs:
  says-hi:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "hi"
          export PYTHON_VERSION=$(python --version)
          echo "::set-env name=PYTHON_VERSION::$PYTHON_VERSION"
      - name: Print Python Version
        run: echo $PYTHON_VERSION