name: Our first pipeline!

on: [push]

jobs:
  says-hi:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "hi"
          export PYTHON_VERSION=$(python --version)
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV
      - name: Print Python Version
        run: echo "${{env.PYTHON_VERSION}}" #Better work!