name: Our first pipeline!

on: [push]

jobs:
  says-hi:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "hi"
          export PYTHON_VERSION=$(python --version)
      - name: Print Python Version
        run: echo $PYTHON_VERSION